# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:eLKIRoj1dA+HqKDm71t+IsZ7,iv:f0ZzSOdM+cpEdp7RnjmFlOGHAL/gg0742P3o/Im4RxQ=,tag:NHqICJAA7dWsmEwwUscK2A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1Rzi+z3jVjE8+Axy2Gs65qC8d6z66tBwsxaaaSfNoIeRBh8JwXpXlPaACkgy,iv:UlE7sMz2lccF8ToK5MuFOPrRFP3nR7bKZTGcG/9iRHc=,tag:NcuPKPCGO/sJNXOeO2vvTA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZYakgyZGwweWkzd0ZT
        SEVuVjBmWTVTdVUrdUlQLzNsb24zRDREd3dJCm81elRvYVZBRExyWnp1TTZud1Bz
        Y3AzVnI2NnZlWGFGRUtCQ2tUUUF5bzAKLS0tIEFqV3FGWEVwczVIMm5rR0Y5UXU1
        cTgyY1NYYTJ1QVo0YmlxVDNuU2cxbTgKj6fZACWYgb25ZD8miA3WJ8OXWyEdEFzI
        gH6ie5tSTSGuFdoDMAF/MKTUcgxNbr90EL1EPP8//4MItBtJhs1M1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T22:48:08Z"
  mac: ENC[AES256_GCM,data:Gw1U79//jcrbYLXaQpH2nrT4WCCBhc+JbTamcnaJeIJjOWUt/uuhNGQQerkxfdU3PWwJAHMCZCufK4TffqpmY3yT+7nrOQDA8RHaxq4l0BjnnSF4fv/O41z1HGWkRIq2AsdwVYSrK4qq/2vDBl1vyBHR7IRwq8bA2/mtMIjTV0c=,iv:MZ054KjbPW3RgsMxXw6A+9FvTnG1j7MLVTHXbVf36Ws=,tag:fSJecIJRwiRaL2DfMP5wSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
