apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  meilisearch_master_key: ENC[AES256_GCM,data:YUZONFugeWd68MsClHBZL4y7y9M8okddKwJP6QZYUhwWdCSQ,iv:LavBJGy+g0Fc4YNCWksPArsdsmPzm3M8CDA3BbWxgJ8=,tag:dKqr5biq5Vmmwizzt4W77g==,type:str]
  nextauth_secret: ENC[AES256_GCM,data:HOax5wClyrwTgy3e74hc5xRTI9xcqMpx13fKVvHjyAJ3wtxFJ3pXo+1MSNo=,iv:sqBD9HScDsvwK10/cbB6N/1iI02uSdtn/3hERSe1l74=,tag:l4K/8XVGRKxNP3ynKViP7Q==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdExxMGpGR1Y0VTAxT0hZ
        RlNiRkt6QkFFRE4vMU5JWWJqak1GblJrcHhBCjdxdDBVQW85emNGMDM1VndLUTZV
        OC9rRHhVelRCT0RwNWZNTWNPZDBVTkEKLS0tIEFiZWpWSC8rTVRWV1JzSVlSYUdB
        T2d3TnpqM3B0bEM1V290YURaaUFhTFEKdZCt2RbvUOHcm1/YtVxZyWYzW3NzftjI
        TWk3nn/HGGPqipJmrOSnxki36082kITrSbb+LrICyfZ8oENl67QZ7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T20:57:43Z"
  mac: ENC[AES256_GCM,data:ubFGTd1JLI3feQbI/2XraxyEsaYTdudRX0HXSu4OG1qvmT5ckUZYPP3i0vDi2SCvd41Vmch3BrWeOTCU7eyKRlShEC6aYanMDu30Cm8wKlZlBmfFaWx2knMEWpsAf8pgNa1urkL5qHfkv9RxgFSF3vx2vpafpL3X7SK9RQo6i1Y=,iv:l7ZdN1QJkyJTGOy4ylwHJ+K6/3vLV7uDDYqFhvSXYFo=,tag:5pUqDK1NRJawAKVzg022Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
