apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:Qsnv/ZL5pyUIE6iBAZYZjy3ZLvIG8LTejEgF9iHkT+t6iNxt,iv:SPIwf7X9V1pEMph9y+LKbnfoJ6JNHHJKszWgb0MAN78=,tag:pG72KhMcYa09nMogYJXMKg==,type:str]
  nextauth_secret: ENC[AES256_GCM,data:HOax5wClyrwTgy3e74hc5xRTI9xcqMpx13fKVvHjyAJ3wtxFJ3pXo+1MSNo=,iv:sqBD9HScDsvwK10/cbB6N/1iI02uSdtn/3hERSe1l74=,tag:l4K/8XVGRKxNP3ynKViP7Q==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdExxMGpGR1Y0VTAxT0hZ
        RlNiRkt6QkFFRE4vMU5JWWJqak1GblJrcHhBCjdxdDBVQW85emNGMDM1VndLUTZV
        OC9rRHhVelRCT0RwNWZNTWNPZDBVTkEKLS0tIEFiZWpWSC8rTVRWV1JzSVlSYUdB
        T2d3TnpqM3B0bEM1V290YURaaUFhTFEKdZCt2RbvUOHcm1/YtVxZyWYzW3NzftjI
        TWk3nn/HGGPqipJmrOSnxki36082kITrSbb+LrICyfZ8oENl67QZ7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T16:05:54Z"
  mac: ENC[AES256_GCM,data:YvlpWCdx7W7ABVzVCDS7wW5upUs6mjAP8ZdtiFZkNvrC6S1n7J10zKRowtPqvH/0KOzGRZmB0P7Mn8k6hGjyYZ/TPqhlixTLVWKzosZvl3sDmp0IJgj3EXA2lzbRIv977eDJ/ivbkFppPNa/NlhJsUFxRculRHSAlLBnseQKuVo=,iv:lfWMv64TNLXJND5aMQiR9+eU+Slo6WFeT7EgamDbCjo=,tag:Qo5gZo2Yo6gQgNdFOQElJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
