---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: securitygrant-to-authelia-svc
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: games
  to:
    - group: ""
      kind: Service
      name: authelia
