# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:9Nsj/nS10aNuZYQxoA==,iv:WQRexs8kVgmvbSIdD7zanEzhkyNvh/FLqr7Qi+pRm6w=,tag:4aZYew8cfbKOcnDe30IeYA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xzqJAqO+iHAz/ZurqYfUzL+gq5i2soinExHc7q6g6tHfCiQe,iv:GHWhw0Fm46itn8frG1nQcbO5AKJJA86zJCeCJZbCLhs=,tag:PBtAEV2dDQYSi+uVIL2Piw==,type:str]
  DOMAIN_NAME_COUNTRY: ENC[AES256_GCM,data:oE9mlrPTRr597tdkRq1pkw==,iv:Pa06+wxXr7c91Wu0jDqqANsRATBNNg/LjaGRBgZy7k0=,tag:0yVb3JBM6kdDCdPJr6YBMg==,type:str]
  DOMAIN_GARBLE_DEV: ENC[AES256_GCM,data:sQ/szmhf2cWf,iv:E7RMm4YD8GCMaslRLDliwEL1y8A6uND/ux2pa2wa7f4=,tag:uRFOYh+YbmPcnXIu4etAfg==,type:str]
  NFS_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:q21ErT08gFFqR4LV,iv:UMYYZh8qNABW4+f2ykFGlpYgv1ZJUF5Hu0OAXUpjek4=,tag:iR90ANKZpp+xRkq08gtL3g==,type:str]
  MUSIC_ASSISTANT_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:xghSba1VASXbxKrG,iv:fi+OuacNMtxIkdVlvyhDxRNOFv9VK7IRALDCcMJVfR8=,tag:ykJ2G6Vsq7g3bYjg7iP+Bw==,type:str]
  HOME_ASSISTANT_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:SkFNXDy4WuXF/UKO,iv:Ci4I8yUupKRMfqGvm6zZBxXepv3Dh4i7KPkuWIDa0Ck=,tag:ta+FohX0kaoomnwP/4ox1Q==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:Dh/sGwPf69FavFcrR0VBzw==,iv:jO7GU6nJbnL6/wPFN8pf5mFP2A+yacQkKoueoZxt7zY=,tag:qozjGEH7LWesGge+DywNVQ==,type:str]
  BREVO_SMTP_USERNAME: ENC[AES256_GCM,data:5RhGsecVG0Qa,iv:Nw1WtLTOkKlaB2MnhDyy/py+2vBWMxJ2S+Z72cJItlw=,tag:7/LD5Oj0VRrTlqb5ueCpWA==,type:str]
  SECRET_HOMELAN_IPV4: ENC[AES256_GCM,data:0gqU+4gsXPWUlt74qk1gwq4=,iv:4rg5JEa+2DO0ajo8NiVySq/fd3bi7OZMufvPSm9VmFE=,tag:1P8WU4BUZ+FK/VvFpkWVmA==,type:str]
  SECRET_VICTOR_HOME_IP: ENC[AES256_GCM,data:H2upG96mhtJ1WGUXeM1pL3A=,iv:cM1MAZ1a+jiKcynLgFcuHPeJ3Ld0Wph8vI1gzlppTHs=,tag:aL1oDxMmhI8qR4jTMGZ8TQ==,type:str]
  SECRET_STIJN_HOME_IPV4: ENC[AES256_GCM,data:A6N7WKQ0t+eiXwprLKUCeA==,iv:N898evH2Biookux9nJPMsVjckTfC5Z4o4SxdVsz7X+A=,tag:b1cArD9/7qeqp5MrzK8WWw==,type:str]
  SECRET_STIJN_HOME_IPV6: ENC[AES256_GCM,data:r4Oy/KRIEFABmeNU62E69lH67z/Zn10SrYlkeI0Zm+rThMVF,iv:/wyvxkm0eawf7DbAbbAwrfOQuduqUxLFaxRQhB7a5fw=,tag:gjsrwGpEIX4qGooAmhRJyg==,type:str]
  SECRET_J_HOME_IP: ENC[AES256_GCM,data:E6QT/oX1b6nKRhXfwo548iU=,iv:7WdA2BSOQe1ESCMvVYcKFEwzZnH0MTD+6vYYpN89oPI=,tag:MAOPWbSo4xBNAn+iNK/t2w==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdW5YQW90TXR5N01CMTN0
        Q3lZSkVFWUIrb3JTNzRwNFJPekpzYU9zLzA4Cm15TmIvbmdNaUNYcWpGeWpnYnhD
        YXFNcW9kbjVzUmE5UkVVU04xeml1cmMKLS0tIEl5Vm1kY3lFS1VJbThPQUd0N3dv
        NnQxNE1ndCtxeTE4RlB6YlFEZG1Bb2MK3usw8zocUacgSvhjOVBU4tmg03gGVmGs
        RP776UpJMrp9X2GAUgKdRL0MPPcRz2Wqjs+7Lv+toP4RxzLsysxfHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T17:08:32Z"
  mac: ENC[AES256_GCM,data:b0UOVjvZBuhE6UHtt9BIMbRPaES+Mg4hjbDUuYNrvmSybjO2/tOOw4TjC8iM7cdDFY4lGC6I0iENIa/7J3DXH7hHlwYdnYJZFjNBknj7gbZEKWXaxxGyBZx2e1llSDI9SUSuGjoVB7MY1N8ZNv+T46/2CrdqYqtYZgSy3Oa3uRY=,iv:Oo6qH/2XOhiaORu5UgXepdeP+upLqfMna7vdXTuGj34=,tag:54E5Z3zFHoVlQ0eoe07L4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
