---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./echo-server/ks.yaml
  - ./echo-server-internal/ks.yaml
  - ./ocis/ks.yaml
  - ./continuwuity/ks.yaml
  - ./karakeep/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: default
    target:
      kind: Namespace
