---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "foundryvtt-victor-extauthz"
spec:
  targetRefs:
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
      name: "foundryvtt-victor"
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
      name: "foundryvtt-victor-files"
  extAuth:
    headersToExtAuth:
      - "X-Forwarded-For" # this is here so we can get the real IP
      - "X-Real-Ip" # Needed to make Anubis happy
      - "accept"
      - "cookie"
      - "authorization"
      - "proxy-authorization"
      - "x-forwarded-proto"
    failOpen: false
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: "authelia"
          namespace: "auth"
          port: 8923
      path: "/api/authz/ext-authz/"
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
