---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "nfs-to-s3"
spec:
  sourcePVC: "nfs-backups"
  trigger:
    schedule: "20 2 * * *"
  restic:
    copyMethod: Direct
    repository: "nfs-to-volsync-s3"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    storageClassName: ""
    accessModes: ["ReadWriteMany"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    pruneIntervalDays: 21
    retain:
      daily: 9
