# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nfs-to-volsync-s3
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kNa2v4E1p8/nNZM29gzexWQJIIxajZdDcVYCQOq49W/lfz5c2gDJb4Y6VwPnyLaglUmnFg==,iv:eFGCMypcP+2WkCu+kTqaR6w7CvCAxohkSS9WGMqLrqM=,tag:7ofl/HxkusCAwyJf7oX4Sw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:PWZRjwpO+xm6J8FWib/X97SFOSTRQNR715sRp+9xgAnSDKK3adH2QSPgZE3G,iv:KXYOUTusCynTh1SiwoLW6y8EeM7bxOlXEkRi2kuqXUw=,tag:2x8e+BTJrdpvsSpYahVoEQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o+ClJrTySyI7YGxfH8vO/QECoLABZvg8iX/Ki7Am2oA=,iv:Wco9SWAtSfNGka72ZH49hMIDjWsU6zhKRID3csl7P28=,tag:0RhjOP2tQzxXIedD3Wottw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:r06FTYukXPl0EOAAhdSotULzOpRuZwBKAy7jq/D2sic=,iv:STBPeOlF0vJEiiJ/h5p5AUWnkTG21wJhq/9NiDHkZJ0=,tag:uzsaRuZ9EGW/lq2DacABjA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZYakgyZGwweWkzd0ZT
        SEVuVjBmWTVTdVUrdUlQLzNsb24zRDREd3dJCm81elRvYVZBRExyWnp1TTZud1Bz
        Y3AzVnI2NnZlWGFGRUtCQ2tUUUF5bzAKLS0tIEFqV3FGWEVwczVIMm5rR0Y5UXU1
        cTgyY1NYYTJ1QVo0YmlxVDNuU2cxbTgKj6fZACWYgb25ZD8miA3WJ8OXWyEdEFzI
        gH6ie5tSTSGuFdoDMAF/MKTUcgxNbr90EL1EPP8//4MItBtJhs1M1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T00:01:26Z"
  mac: ENC[AES256_GCM,data:lE4YwUcnCXVCKln4IZDfMUrqLhM4MX8h3/49UNU0fbOW2HC4L2dhsDGMpgs2D5dJy4DKxU1dnFlY/c9NzpCag04bwX+hJRA/59ESInyQXo8U6keeTKoJoLONd0njgxFSwkxankNC+j/Cdm+0iL0Ld4yHC8sJlK29dJw4n8OCd94=,iv:2LtMx4krHAa5AvhSpe4SoUsQmskDcf2+7aefFudvUR8=,tag:FXgp5sjIYbKH32Y4kzGKzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
