---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.11.25
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    fullnameOverride: "victoria-logs"
    retentionPeriod: "14d"
    server:
      persistentVolume:
        enabled: true
        storageClassName: "ceph-block"
        size: "20Gi"
      ingress:
        enabled: true
        ingressClassName: "internal"
        pathType: "Prefix"
        hosts:
          - name: "vlogs.${CLUSTER_DOMAIN}"
            path:
              - "/"
            port: "http"
      # route:
      #   enabled: true
      #   hostnames:
      #     - victoria-logs.turbo.ac
      #   parentRefs:
      #     - name: envoy-internal
      #       namespace: network
      #   extraRules:
      #     - filters:
      #         - type: RequestRedirect
      #           requestRedirect:
      #             path:
      #               type: ReplaceFullPath
      #               replaceFullPath: /select/vmui/
      #             statusCode: 302
      #       matches:
      #         - path:
      #             type: Exact
      #             value: /
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
