---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-s3"
spec:
  sourcePVC: "${CLAIM:=${APP}}"
  trigger:
    schedule: "20 3 * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    repository: "${APP}-volsync-s3"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    pruneIntervalDays: 21
    retain:
      daily: 9
