# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-s3
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:CoBY5Yvt/EtFgURKqHpJf5EOjHXXpNDjmYxK1smH1Ikvfu8WlvSbEmShgBgsYbvauUNgfH3yyQ==,iv:Q4QUe2LqVZdIR9TIlRIag8WhJW8dA2oBST7lFp+GT68=,tag:F77l0ZbF9UTFH3zGPELGog==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:PWZRjwpO+xm6J8FWib/X97SFOSTRQNR715sRp+9xgAnSDKK3adH2QSPgZE3G,iv:KXYOUTusCynTh1SiwoLW6y8EeM7bxOlXEkRi2kuqXUw=,tag:2x8e+BTJrdpvsSpYahVoEQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o+ClJrTySyI7YGxfH8vO/QECoLABZvg8iX/Ki7Am2oA=,iv:Wco9SWAtSfNGka72ZH49hMIDjWsU6zhKRID3csl7P28=,tag:0RhjOP2tQzxXIedD3Wottw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:r06FTYukXPl0EOAAhdSotULzOpRuZwBKAy7jq/D2sic=,iv:STBPeOlF0vJEiiJ/h5p5AUWnkTG21wJhq/9NiDHkZJ0=,tag:uzsaRuZ9EGW/lq2DacABjA==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZYakgyZGwweWkzd0ZT
        SEVuVjBmWTVTdVUrdUlQLzNsb24zRDREd3dJCm81elRvYVZBRExyWnp1TTZud1Bz
        Y3AzVnI2NnZlWGFGRUtCQ2tUUUF5bzAKLS0tIEFqV3FGWEVwczVIMm5rR0Y5UXU1
        cTgyY1NYYTJ1QVo0YmlxVDNuU2cxbTgKj6fZACWYgb25ZD8miA3WJ8OXWyEdEFzI
        gH6ie5tSTSGuFdoDMAF/MKTUcgxNbr90EL1EPP8//4MItBtJhs1M1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T22:53:25Z"
  mac: ENC[AES256_GCM,data:3Ag9YUymWaCD+KYmP6UmZlRs6Qwmm++4RugpURGe3yVA9myw/8p4hbgx13oxh8mgbh1OfdW0taor1PUNnJFQErxu4ITJMSIKKu+E6Z4Et4jFvsk+Rn+hw+kDputZku2oD5z55srjcE1FEWqFTc/Wrgj0vfpIgBIj2Gwb/EfB8ZY=,iv:0oN/DpTO1GTxBuKm/ZtSUyiz8tkPNx2SgPYUaJNs9io=,tag:60ZO6lTn1eC6p0qzTCq86g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
