---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: et-user
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/clusterrole-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-all-workloads
rules:
  - apiGroups: ["v1", "apps/v1"]
    resources:
      - "pods"
      - "deployments"
      - "statefulsets"
      - "persistentvolumeclaims"
    verbs: ["get", "watch", "list"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/clusterrole-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-all-cnpg-things
rules:
  - apiGroups: ["postgresql.cnpg.io/v1"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/clusterrolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-all-cnpg-things-et-user
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: read-all-cnpg-things
subjects:
  - kind: ServiceAccount
    name: et-user
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/clusterrolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-all-workloads-et-user
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: read-all-workloads
subjects:
  - kind: ServiceAccount
    name: et-user
