---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoy-gateway/ks.yaml
  - ./external/ks.yaml
  - ./internal/ks.yaml
  - ./tailscale/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: network
    target:
      kind: Namespace
